Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [14]:
import numpy as np
def Matrix(): 
    x = np.array([1,2,3,4,5,6])
    N = len(x)
    matrix = np.column_stack([x**(N-i-1) for i in range(N)])
    print(matrix)
Matrix()

[[   1    1    1    1    1    1]
 [  32   16    8    4    2    1]
 [ 243   81   27    9    3    1]
 [1024  256   64   16    4    1]
 [3125  625  125   25    5    1]
 [7776 1296  216   36    6    1]]


Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [52]:
a=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
n=3

In [53]:
np.cumsum(a, dtype=float)

array([  3.,   8.,  15.,  17.,  25.,  35.,  46., 111., 183., 264., 363.,
       463., 613.])

In [54]:
asum = np.cumsum(a, dtype=float)

In [55]:
print(asum[n:])
print(asum[:-n])

[ 17.  25.  35.  46. 111. 183. 264. 363. 463. 613.]
[  3.   8.  15.  17.  25.  35.  46. 111. 183. 264.]


In [56]:
asum[n:] - asum[:-n]

array([ 14.,  17.,  20.,  29.,  86., 148., 218., 252., 280., 349.])

In [57]:
asum[n:] = asum[n:] - asum[:-n]
print(asum[n-1:])

[ 15.  14.  17.  20.  29.  86. 148. 218. 252. 280. 349.]


In [58]:
print((asum[n-1:]) / n)

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]


In [60]:
import numpy as np

def moving_average(a, n):
    asum = np.cumsum(a, dtype=float)
    asum[n:] = asum[n:] - asum[:-n] 
    return asum[n - 1:] / n
a=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
np.array(moving_average(a,3)).round(2)

array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])